line-length = 88

# 末尾スペース・空行まわりをチェックするのは E と W系のルール
# E7xx/E9xx（構文/実行時エラーの可能性）
# W1xx/W5xx（スタイル・フォーマット関連）
# DXXX（ドキュメンテーション文字列関連） 
# F （未使用インポートなどのエラー）
# BXX（バグの可能性）

[lint]
select = ["F", "E", "W", "D101", "B"] 
ignore = []